title: Aldo's Blog
email: aldogatica123@gmail.com
description: >-
  Hi, this is my personal blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aldogatica123

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
