title: Aldo's Blog
email: aldogatica123@gmail.com
description: >-
  aldogatica123
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aldogatica123

google_analytics: UA-133200664-1
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
